name = "aura-os-dashboard"
compatibility_date = "2024-01-01"

[assets]
directory = "./assets"
binding = "ASSETS"

# Sambungan ke Database D1
[[d1_databases]]
binding = "DB"
database_name = "aura-db"
database_id = "14e8a5df-0610-4a45-ae87-5cd86732d584" # GANTI DENGAN ID DARI CLOUDFLARE
